name: Deploy Authentication to EC2 Production

on:
  pull_request:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for frontend
      run: |
        docker build -t kamartinez/password ./password-microservice
        docker build -t kamartinez/captcha ./captcha-microservice

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kamartinez/password
        docker push kamartinez/captcha

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 3.213.102.18
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEYP }}
        script: |
          docker stop password || true
          docker rm password || true
          docker stop captcha || true
          docker rm captcha || true

          docker pull kamartinez/password
          docker pull kamartinez/captcha

          docker run -d --name password -p 8002:8002 --restart unless-stopped kamartinez/password
          docker run -d --name captcha -p 5000:5000 --restart unless-stopped kamartinez/captcha